# Include this file inside the otus.muoviamo.fi server block.

location = /.well-known/assetlinks.json {
    default_type application/json;
    try_files $uri =404;
}

location = /manifest.webmanifest {
    default_type application/manifest+json;
    try_files $uri =404;
    access_log off;
}

location = /service-worker.js {
    default_type application/javascript;
    try_files $uri =404;
    add_header Cache-Control "no-cache" always;
    access_log off;
}
